;
; File generated by cc65 v 2.16 - Git 035baa4
;
	.fopt		compiler,"cc65 v 2.16 - Git 035baa4"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.export		_NMI_flag
	.export		_Frame_Count
	.export		_index
	.export		_Text_Position
	.export		_test
	.export		_TEXT
	.export		_PALETTE
	.export		_Attrib_Table
	.export		_All_Off
	.export		_All_On
	.export		_Load_Palette
	.export		_Reset_Scroll
	.export		_Load_Text
	.export		_main

.segment	"RODATA"

_TEXT:
	.byte	$48,$65,$6C,$6C,$6F,$26,$57,$6F,$72,$6C,$64,$21,$00
_PALETTE:
	.byte	$11
	.byte	$00
	.byte	$00
	.byte	$31
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$15
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$27
	.byte	$00
	.byte	$00
	.byte	$00
	.byte	$1A
_Attrib_Table:
	.byte	$44
	.byte	$BB
	.byte	$44
	.byte	$BB

.segment	"BSS"

.segment	"ZEROPAGE"
.segment	"BSS"
.segment	"ZEROPAGE"
_NMI_flag:
	.res	1,$00
.segment	"ZEROPAGE"
_Frame_Count:
	.res	1,$00
.segment	"ZEROPAGE"
_index:
	.res	1,$00
.segment	"ZEROPAGE"
_Text_Position:
	.res	1,$00
.segment	"BSS"
_test:
	.res	1,$00

; ---------------------------------------------------------------
; void __near__ All_Off (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_Off: near

.segment	"CODE"

;
; PPU_CTRL = 0;
;
	lda     #$00
	sta     $2000
;
; PPU_MASK = 0; 
;
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ All_On (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_All_On: near

.segment	"CODE"

;
; PPU_CTRL = 0x90; // screen is on, NMI on
;
	lda     #$90
	sta     $2000
;
; PPU_MASK = 0x1e; 
;
	lda     #$1E
	sta     $2001
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Palette (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Palette: near

.segment	"CODE"

;
; PPU_ADDRESS = 0x3f;
;
	lda     #$3F
	sta     $2006
;
; PPU_ADDRESS = 0x00;
;
	lda     #$00
	sta     $2006
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	sta     _index
L00B6:	lda     _index
	cmp     #$10
	bcs     L00B7
;
; PPU_DATA = PALETTE[index];
;
	ldy     _index
	lda     _PALETTE,y
	sta     $2007
;
; for( index = 0; index < sizeof(PALETTE); ++index ){
;
	inc     _index
	jmp     L00B6
;
; PPU_ADDRESS = 0x23;
;
L00B7:	lda     #$23
	sta     $2006
;
; PPU_ADDRESS = 0xda;
;
	lda     #$DA
	sta     $2006
;
; for( index = 0; index < sizeof(Attrib_Table); ++index ){
;
	lda     #$00
	sta     _index
L00B8:	lda     _index
	cmp     #$04
	bcs     L0042
;
; PPU_DATA = Attrib_Table[index];
;
	ldy     _index
	lda     _Attrib_Table,y
	sta     $2007
;
; for( index = 0; index < sizeof(Attrib_Table); ++index ){
;
	inc     _index
	jmp     L00B8
;
; }
;
L0042:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Reset_Scroll (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Reset_Scroll: near

.segment	"CODE"

;
; PPU_ADDRESS = 0;
;
	lda     #$00
	sta     $2006
;
; PPU_ADDRESS = 0;
;
	sta     $2006
;
; SCROLL = 0;
;
	sta     $2005
;
; SCROLL = 0;
;
	sta     $2005
;
; }
;
	rts

.endproc

; ---------------------------------------------------------------
; void __near__ Load_Text (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_Load_Text: near

.segment	"CODE"

;
; if (Text_Position < sizeof(TEXT)){
;
	lda     _Text_Position
	cmp     #$0D
	bcs     L00B9
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xca + Text_Position; // about the middle of the screen 21d0
;
	lda     _Text_Position
	clc
	adc     #$CA
	sta     $2006
;
; PPU_DATA = TEXT[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT,y
	sta     $2007
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xea + Text_Position; // one line down = add 0x20 to the low bit
;
	lda     _Text_Position
	clc
	adc     #$EA
	sta     $2006
;
; PPU_DATA = TEXT[Text_Position];
;
	ldy     _Text_Position
	lda     _TEXT,y
	sta     $2007
;
; ++Text_Position; 
;
	inc     _Text_Position
;
; else {
;
	rts
;
; Text_Position = 0;
;
L00B9:	lda     #$00
	sta     _Text_Position
;
; PPU_ADDRESS = 0x21;
;
	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xca;
;
	lda     #$CA
	sta     $2006
;
; for ( index = 0; index < sizeof(TEXT); ++index ){
;
	lda     #$00
	sta     _index
L00BA:	lda     _index
	cmp     #$0D
	bcs     L00BB
;
; PPU_DATA = 0; // clear the text by putting tile #0 in its place
;
	lda     #$00
	sta     $2007
;
; for ( index = 0; index < sizeof(TEXT); ++index ){
;
	inc     _index
	jmp     L00BA
;
; PPU_ADDRESS = 0x21;
;
L00BB:	lda     #$21
	sta     $2006
;
; PPU_ADDRESS = 0xea;
;
	lda     #$EA
	sta     $2006
;
; for ( index = 0; index < sizeof(TEXT); ++index ){
;
	lda     #$00
	sta     _index
L00BC:	lda     _index
	cmp     #$0D
	bcs     L00AB
;
; PPU_DATA = 0; // clear the text by putting tile #0 in its place
;
	lda     #$00
	sta     $2007
;
; for ( index = 0; index < sizeof(TEXT); ++index ){
;
	inc     _index
	jmp     L00BC
;
; }
;
L00AB:	rts

.endproc

; ---------------------------------------------------------------
; void __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; All_Off();   // turn off screen
;
	jsr     _All_Off
;
; Load_Palette();
;
	jsr     _Load_Palette
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; All_On();   // turn on screen
;
	jsr     _All_On
;
; while (NMI_flag == 0); // wait till NMI
;
L00BD:	lda     _NMI_flag
	beq     L00BD
;
; NMI_flag = 0;
;
	lda     #$00
	sta     _NMI_flag
;
; if (Frame_Count == 30){ // wait 30 frames = 0.5 seconds
;
	lda     _Frame_Count
	cmp     #$1E
	bne     L00BD
;
; Load_Text();
;
	jsr     _Load_Text
;
; Reset_Scroll();
;
	jsr     _Reset_Scroll
;
; Frame_Count = 0;
;
	lda     #$00
	sta     _Frame_Count
;
; ++test; // dummy, just making sure this compiles into the BSS section 0x300
;
	inc     _test
;
; while (1){   // infinite loop
;
	jmp     L00BD

.endproc

